# Generated by Django 4.2.13 on 2024-05-29 09:47

import ckeditor.fields
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRLapp', '0002_activity_falcuty_regulation_point_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='confirm',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='descriptions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
