# Generated by Django 4.2.13 on 2024-05-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRLapp', '0004_activity_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='descriptions',
            new_name='description',
        ),
    ]
