# Generated by Django 4.2.13 on 2024-05-30 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRLapp', '0005_rename_descriptions_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uclass', to='DRLapp.class'),
        ),
    ]
