# Generated by Django 4.2.13 on 2024-06-13 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRLapp', '0006_user_uclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='regulation',
        ),
        migrations.AddField(
            model_name='activity',
            name='point',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='regulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulation', to='DRLapp.regulation'),
        ),
        migrations.AlterField(
            model_name='point',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='DRLapp.activity'),
        ),
    ]
