# Generated by Django 4.2.13 on 2024-06-18 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRLapp', '0007_remove_activity_regulation_activity_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='regulation',
        ),
        migrations.AddField(
            model_name='activity',
            name='regulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulation', to='DRLapp.regulation'),
        ),
        migrations.AddField(
            model_name='point',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='point',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='falcuty',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='falcuty',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
