# Generated by Django 4.2.13 on 2024-06-18 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRLapp', '0008_remove_point_regulation_activity_regulation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='activity',
        ),
        migrations.AddField(
            model_name='point',
            name='regulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulationPoint', to='DRLapp.regulation'),
        ),
    ]
